name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image: bazel-linux
      run: docker build bazel-linux/ --file Dockerfile --tag docker.pkg.github.com/michael-tu/docker-images/bazel-linux:latest
